//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordTools.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WordTools.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap icons8_about_90 {
            get {
                object obj = ResourceManager.GetObject("icons8_about_90", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap icons8_better_150 {
            get {
                object obj = ResourceManager.GetObject("icons8_better_150", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap icons8_clean_96 {
            get {
                object obj = ResourceManager.GetObject("icons8_clean_96", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap icons8_deepseek_150 {
            get {
                object obj = ResourceManager.GetObject("icons8_deepseek_150", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap icons8_deepseek_48 {
            get {
                object obj = ResourceManager.GetObject("icons8_deepseek_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap icons8_more_70 {
            get {
                object obj = ResourceManager.GetObject("icons8_more_70", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap icons8_rewrite_150 {
            get {
                object obj = ResourceManager.GetObject("icons8_rewrite_150", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap icons8_satellite_70 {
            get {
                object obj = ResourceManager.GetObject("icons8_satellite_70", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap icons8_selection_48 {
            get {
                object obj = ResourceManager.GetObject("icons8_selection_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap icons8_setting_128 {
            get {
                object obj = ResourceManager.GetObject("icons8_setting_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap icons8_sparkling_100 {
            get {
                object obj = ResourceManager.GetObject("icons8_sparkling_100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap icons8_spellcheck_70 {
            get {
                object obj = ResourceManager.GetObject("icons8_spellcheck_70", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap icons8_spellcheck_all_100 {
            get {
                object obj = ResourceManager.GetObject("icons8_spellcheck_all_100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap icons8_table_all_100 {
            get {
                object obj = ResourceManager.GetObject("icons8_table_all_100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap icons8_table_single_96 {
            get {
                object obj = ResourceManager.GetObject("icons8_table_single_96", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap icons8_text_generation_150 {
            get {
                object obj = ResourceManager.GetObject("icons8_text_generation_150", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        /// 获取图标的Base64编码字符串，用于Ribbon XML
        /// </summary>
        /// <param name="iconName">图标资源名称</param>
        /// <returns>Base64编码的图标数据</returns>
        internal static string GetIconBase64(string iconName)
        {
            try
            {
                System.Drawing.Bitmap bitmap = null;
                
                switch (iconName)
                {
                    case "icons8_about_90":
                        bitmap = icons8_about_90;
                        break;
                    case "icons8_better_150":
                        bitmap = icons8_better_150;
                        break;
                    case "icons8_clean_96":
                        bitmap = icons8_clean_96;
                        break;
                    case "icons8_deepseek_150":
                        bitmap = icons8_deepseek_150;
                        break;
                    case "icons8_deepseek_48":
                        bitmap = icons8_deepseek_48;
                        break;
                    case "icons8_more_70":
                        bitmap = icons8_more_70;
                        break;
                    case "icons8_rewrite_150":
                        bitmap = icons8_rewrite_150;
                        break;
                    case "icons8_satellite_70":
                        bitmap = icons8_satellite_70;
                        break;
                    case "icons8_selection_48":
                        bitmap = icons8_selection_48;
                        break;
                    case "icons8_setting_128":
                        bitmap = icons8_setting_128;
                        break;
                    case "icons8_sparkling_100":
                        bitmap = icons8_sparkling_100;
                        break;
                    case "icons8_spellcheck_70":
                        bitmap = icons8_spellcheck_70;
                        break;
                    case "icons8_spellcheck_all_100":
                        bitmap = icons8_spellcheck_all_100;
                        break;
                    case "icons8_table_all_100":
                        bitmap = icons8_table_all_100;
                        break;
                    case "icons8_table_single_96":
                        bitmap = icons8_table_single_96;
                        break;
                    case "icons8_text_generation_150":
                        bitmap = icons8_text_generation_150;
                        break;
                    default:
                        return null;
                }
                
                if (bitmap != null)
                {
                    using (var ms = new System.IO.MemoryStream())
                    {
                        bitmap.Save(ms, System.Drawing.Imaging.ImageFormat.Png);
                        return System.Convert.ToBase64String(ms.ToArray());
                    }
                }
                
                return null;
            }
            catch
            {
                return null;
            }
        }
    }
}
